### PR TITLE
Fix 4D vector parsing anomaly

### PR DESCRIPTION
**Pull request by BentSm**
When expecting a 4D vector, the parser would erroneously treat a 3D vector as if it had 4 components, despite only setting 3 (so that the fourth component would retain whatever value was in that memory location).  (More precisely, Parse_Num_Factor would fail to update `*Terms` when parsing a 3D vector token if `*Terms>3`.)  This would cause, e.g., `julia_fractal{2/9*x}` to get parsed as if one had written `julia_fractal{2/9*<1,0,0,9>}`.

This fixes that issue.  (I also removed a nearby comment that no longer makes much sense.)

### CODE REVIEW

**Comment by c-lipka** [comment]
Thanks for this fix!

Just for the records: Are you aware of any place where this had been reported previously (GitHub issue, the old FlySpray tracker, one of the newsgroups, or anything along those lines)?

**Comment by BentSm** [comment]
No, but it's possible; I didn't check.

**Comment by c-lipka** [comment]
If you happen to have the time, that would be great.

**Comment by BentSm** [comment]
After a little looking, it does not appear to have been reported.

**Pull request merged**
