### PR TITLE
Remove boost TR1

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes incompatibility with recent boost versions https://github.com/POV-Ray/povray/issues/317
cc @ilovezfs

### CODE REVIEW

**Comment by wfpokorny** [comment]
First, It happens many of the core developers are occupied with other than POV-Ray at the moment so response might be slow. 

I was not involved in the original implementation, but I know from other discussions the 'belief' was the ' #include <boost/tr1/*' style would just work when the code implementation showed up in the base compiler while not breaking those with older installs and compilers.  

However, digging a little just now I found: 

http://www.boost.org/doc/libs/1_64_0/doc/html/boost_tr1/usage.html#boost_tr1.usage.native

which looks to me like we should make the changes you've made but also update the *nix build system for another boost include in:  boost-install-path/boost/tr1/tr1 as a start for compatibility. Looks like that tr1/tr1 include exists back to at least boost 1.58. 

I know our boost m4 macros - which are just copied into <source_install>povray/unix/config with an ax_prefix are somewhat out of date with current ones, but I also see nothing in my copies from March which would add such an include by default. So...   

While it is a Holiday weekend here, I've got other commitments. Would you be willing to hack your  branch <source_install>povray/unix/configure.ac file in the boost section so the line: 

  `CPPFLAGS="$CPPFLAGS $BOOST_CPPFLAGS"  # append`

reads: 

  `CPPFLAGS="$CPPFLAGS $BOOST_CPPFLAGS -I/usr/include/boost/tr1/tr1"  # append`

? 

After which, test if your compiles still work and if so, commit and push to this pull request to see if it fixes any of the backward compatibility issues in the github integration tests.  

OK if not. Just might be a while until someone else can look at this. 

Suppose even if adding this include works, it's not what we should do long term given, for one, the boost includes might not always be in that specific location.  The link above also lists other issues.  Must be too the tr1 versions just don't exist in 1.65 onward which implies boost forcing the use of compilers with inbuilt support I guess - at least with base boost installs? Wonder if the tr1 stuff can still be installed specifically?

**Comment by c-lipka** [comment]
It appears that boost/tr1 has been deprecated since boost 1.56, which was released in August 7, 2014.

In my optinion the removal of that library was a poor choice, as it removes a crucial piece of the puzzle to keep smart-pointer-using code compatible across C++ standard generations.

For our current codebase (previously referred to as 3.7.1, but redesignated 3.8.0 by now), I think this is the point where we should switch to C++11 entirely.

For our legacy codebase (3.7.0.x) however, I'm not sure if that would be the right choice. Aiming for compatibility with C++11 (and C++14 and whatnot) and modern boost versions is one thing; ditching compatibility with compilers that were up-to-date when 3.7.0 was originally developed is an entirely different thing.

In my opinion, the proposed changes are therefore not an option. We should go for something smarter.

**Comment by ilovezfs** [comment]
>For our current codebase (previously referred to as 3.7.1, but redesignated 3.8.0 by now), I think this is the point where we should switch to C++11 entirely.

This PR is against master, which I assume is the 3.8.0 branch, no?

**Comment by c-lipka** [comment]
Sorry, skimming over this pull request I got mislead by the homebrew reference citing 3.7.0.3.

`master` is actually not the 3.8.0 branch; instead, it is supppsed to "inherit" from `release/v3.8.0`.

I had already prepared a set of changes to the modern (post-3.7.0) codebase to make the transition to C++11. I'll have a look whether I already included the removal of boost/tr1 dependency.

**Comment by ilovezfs** [comment]
@c-lipka Ah, OK. For 3.7.0.3 in Homebrew, we needed a modified version of this PR, which is here: https://github.com/Homebrew/formula-patches/pull/173.

**Comment by c-lipka** [comment]
See commit 1dbca0b.

**Pull request closed without merging**
